---
title: Design, Technology, and Innovation Projects - City of Austin
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:collection/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: sidebar-page
    nav_from_collection: projects
    image_path: "/assets/img/projects/project-tile-placeholder.jpg"
email: innovationfellows@austintexas.gov
description: 'Design, Technology, and Innovation Projects at the City of Austin

'
baseurl: 
url: http://projects.austintexas.io
twitter:
  username: civiqueso
medium_url: https://medium.com/city-of-austin-design-technology-innovation
zilker_theme: light
markdown: kramdown
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
sass:
  sass_dir: assets/stylesheets/
permalink: pretty
exclude:
- node_modules
- gulpfile.js
- Gemfile
- Gemfile.lock
- npm-debug.log
- "/screenshots"
- "/assets/stylesheets/bourbon"
- "/assets/stylesheets/bourbon-neat"
- "/assets/uswds/stylesheets"
- "/assets/uswds/js"
- ".bundle"
- "/vendor"
- _bourbon
- _bourbon-neat
- _uswds
